#!/bin/sh

choices="poweroff\nreboot\nlock\nlogout"
chosen=$(echo "$choices" | dmenu -i -c -l 20)

case "$chosen" in
    poweroff) sudo systemctl poweroff ;;
    reboot) sudo systemctl reboot ;;
    logout) pkill -KILL -u $(whoami) ;;
    lock) slock ;;
esac
